name = "cloudflare-scraper"
main = "driver.js"

workers_dev = true
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-03-05"
upload_source_maps = true


[browser]
binding = "browser"

[observability.logs]
enabled = true