name = "main-driver"
main = "index.js"
compatibility_date = "2024-06-01"

[triggers]
crons = ["0 6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "scraper-data"
database_id = "<YOUR_DB_ID>"
